name: tracecolor-github-repo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - colorlog>=6.0.0  # Install via conda
  - pytest           # Install via conda
  - pytest-cov       # Install via conda
  - pip              # Keep pip for any pip-only packages if needed later
